service: product-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

  environment:
    SNS_TOPIC_ARN:
      Ref: SNSTopic

  iamRoleStatements:
    - Effect: Allow
      Action: "sqs:*"
      Resource:
        - Fn::GetAtt:
          - SQSQueue
          - Arn
    - Effect: Allow
      Action: "sns:*"
      Resource:
        Ref: SNSTopic

custom:
  webpack:
    webpackConfig: '../webpack.config.js'
    includeModules: true
  serverless-offline:
    httpPort: 4000

plugins:
  - 'serverless-webpack'
  - 'serverless-offline'
  - 'serverless-dotenv-plugin'

functions:
  getProductsList:
    handler: src/handlers/getProductsList/getProductsList.getProductsList
    events:
      - http:
          path: product
          method: get
          cors: true
  getProductById:
    handler: src/handlers/getProductById/getProductById.getProductById
    events:
      - http:
          path: product/{productId}
          method: get
          cors: true
  createProduct:
    handler: src/handlers/createProduct/createProduct.createProduct
    events:
      - http:
          path: product
          method: post
          cors: true
  catalogBatchProcess:
    handler: src/handlers/catalogBatchProcess/catalogBatchProcess.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - SQSQueue
              - Arn

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
    SNSTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: "createProductTopic"
    SNSSubscription1:
      Type: "AWS::SNS::Subscription"
      Properties:
        Endpoint: "${env:SNS_MAIL1}"
        Protocol: "email"
        TopicArn:
          Ref: "SNSTopic"
        FilterPolicy: { "status": ["Success"] }
    SNSSubscription2:
      Type: "AWS::SNS::Subscription"
      Properties:
        Endpoint: "${env:SNS_MAIL2}"
        Protocol: "email"
        TopicArn:
          Ref: "SNSTopic"
        FilterPolicy: { "status": ["Error"] }

  Outputs:
    SQSQueueUrl:
      Value:
        Ref: SQSQueue
    SQSQueueArn:
      Value:
        Fn::GetAtt:
          - SQSQueue
          - Arn
